export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const GET_COLLEGES = 'GET_COLLEGES';
export const SET_USER = 'SET_USER';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_LINKS = 'GET_LINKS';
export const GET_HEADER_INFO = 'GET_HEADER_INFO';
export const SET_LINK_INFO = 'SET_LINK_INFO';
export const DELETE_LINK_INFO = 'DELETE_LINK_INFO';
export const GET_BG_STYLE = 'GET_BG_STYLE';
export const CHOOSE_PURCHASE = 'CHOOSE_PURCHASE';
export const GET_LINK_CLICKS = 'GET_LINK_CLICKS';
export const GET_PROFILE_VIEWS = 'GET_PROFILE_VIEWS';
export const GET_PLANS = 'GET_PLANS';
export const GET_ORDER_HISTORY = 'GET_ORDER_HISTORY';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const CLEAR_CART = 'CLEAR_CART';
export const GET_PENDING_PAYMENT = 'GET_PENDING_PAYMENT';
export const GET_REDEEM_HISTORY = 'GET_REDEEM_HISTORY';
export const GET_BANK_DETAILS = 'GET_BANK_DETAILS';
export const GET_NOT_DELIVERED_SOLD_PRODUCTS = 'GET_NOT_DELIVERED_SOLD_PRODUCTS';
export const GET_DELIVERED_SOLD_PRODUCTS = 'GET_DELIVERED_SOLD_PRODUCTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const GET_RESELLING_PRODUCTS = 'GET_RESELLING_PRODUCTS';
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const SET_RESELLING_PRODUCTS = 'SET_RESELLING_PRODUCTS';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';

//PublicHomePage.js
export const GET_HOME_PAGE_INFO = 'GET_HOME_PAGE_INFO';
export const GET_FEATURED_PRODUCTS = 'GET_FEATURED_PRODUCTS';


//public page
export const GET_SHOP_DETAILS = 'GET_SHOP_DETAILS';
export const GET_PUBLIC_PAGE_SHOP_DETAILS = 'GET_PUBLIC_PAGE_SHOP_DETAILS';
export const GET_PUBLIC_PAGE_HEADER_INFO = 'GET_PUBLIC_PAGE_HEADER_INFO';
export const GET_PUBLIC_PAGE_USER = 'GET_PUBLIC_PAGE_USER';
export const GET_PUBLIC_PAGE_PRODUCTS = 'GET_PUBLIC_PAGE_PRODUCTS';
export const GET_PUBLIC_PAGE_BG_STYLE = 'GET_PUBLIC_PAGE_BG_STYLE';
export const GET_OUR_CHARGES = 'GET_OUR_CHARGES';
export const SET_PUBLIC_PAGE_PRODUCTS = 'SET_PUBLIC_PAGE_PRODUCTS';
export const SET_PUBLIC_PAGE_CATEGORY = 'SET_PUBLIC_PAGE_CATEGORY';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';